apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base configuration for Rain Tracker Historical Import Jobs
# Use overlays (dev/staging/production) for environment-specific customization

namespace: rain-tracker

# Common labels applied to all resources
labels:
  - pairs:
      app: rain-tracker
      component: import-jobs

# Configuration and RBAC resources (always deployed)
resources:
  - import-job-config.yaml
  - historical-import-cronjob.yaml  # CronJobs included in base (suspend in dev via overlay)

# Note: Job templates (non-CronJob) are NOT included as resources because:
# - Jobs with generateName must use 'kubectl create', not 'kubectl apply'
# - They are created on-demand via helper scripts
# - Including them would cause Kustomize to fail on apply
#
# Available job templates (use via scripts):
# - historical-single-year-import.yaml (script: import-water-year.sh)
# - historical-bulk-import.yaml (script: import-bulk-years.sh)
# - fopr-metadata-import.yaml (script: import-fopr-metadata.sh)
#
# These templates can still be used with Kustomize via:
#   kubectl kustomize k8s/jobs/base | sed 's/generateName:/name:/' | kubectl apply -f -
# But it's recommended to use the helper scripts instead.

# Images configuration
images:
  - name: ghcr.io/your-org/rain-tracker-service
    newTag: latest
