codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
        if_ci_failed: error

    patch:
      default:
        target: 80%  # High bar for patch coverage
        threshold: 1%
        base: auto
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "tests/**"           # Test files don't need coverage
  - "src/bin/**"         # CLI tools (separate executables)
  - "migrations/**"      # SQL migrations
  - "src/main.rs"        # Runtime/startup code
  - "src/app.rs"         # Runtime/startup code
  - "src/config.rs"      # Runtime/startup code
  - "src/scheduler.rs"   # Runtime/startup code
  - "src/db/pool.rs"     # Runtime/startup code

# These exclusions match the Makefile coverage targets to ensure
# consistent coverage reporting between local and CI environments.
#
# Note: Logging statements are marked with inline comments in code
# to exclude them from coverage (e.g., // coverage:ignore-line)
