apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rain-tracker
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: rain-tracker=ghcr.io/tdrozdowski/rain-tracker-service
    argocd-image-updater.argoproj.io/rain-tracker.update-strategy: digest
    argocd-image-updater.argoproj.io/rain-tracker.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/tdrozdowski/rain-tracker-service
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: rain-tracker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
