apiVersion: apps/v1
kind: Deployment
metadata:
  name: rain-tracker
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rain-tracker
  template:
    metadata:
      labels:
        app: rain-tracker
    spec:
      containers:
      - name: rain-tracker
        image: rain-tracker-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: rain-tracker-config
        - secretRef:
            name: rain-tracker-secret
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
