apiVersion: apps/v1
kind: Deployment
metadata:
  name: rain-tracker
  namespace: rain-tracker
  annotations:
    argocd-image-updater.argoproj.io/image-list: rain-tracker=ghcr.io/tdrozdowski/rain-tracker-service
    argocd-image-updater.argoproj.io/rain-tracker.update-strategy: digest
    argocd-image-updater.argoproj.io/rain-tracker.allow-tags: regexp:^master-[a-f0-9]{7}$
    argocd-image-updater.argoproj.io/rain-tracker.pull-secret: pullsecret:rain-tracker/ghcr-pull-secret
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rain-tracker
  template:
    metadata:
      labels:
        app: rain-tracker
    spec:
      containers:
      - name: rain-tracker
        image: ghcr.io/tdrozdowski/rain-tracker-service:master-8744b5c
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: rain-tracker-config
        - secretRef:
            name: rain-tracker-db-secret
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
