apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rain-tracker-secret
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgA... # Replace with your sealed secret value
    # Add other secret keys here as needed
  template:
    metadata:
      name: rain-tracker-secret
      namespace: default
    type: Opaque
